project:
  name: cfn-ps-github-enterprise
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  github:
    parameters:
      AccessCIDR: 0.0.0.0/0
      GHELicense: github-enterprise.ghl
      InitialOrganization: quickstart-created-repo
      InitialRepository: repo1
      InstanceType: c4.2xlarge
      KeyPairName: tonynv
      LicenseLocation: quickstart-temp-lic
      ManagementPassword: $[taskcat_genpass_8]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: cfn-ps-github-enterprise/
      SiteAdminUserEmail: none@none.com
      SiteAdminUserPassword: $[taskcat_genpass_8]
      SiteAdminUsername: gitadmin
      VPCCIDR: 10.0.0.0/16
      VolumeType: io1
      ProvisionedIops: '1000'
    template: templates/quickstart-github-enterprise-main.template.yaml
